services:
  core-be:
    build:
      context: .
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      SCRAPER_URL: ${SCRAPER_URL}
      FE_URL: ${FE_URL}
      PORT: ${PORT}
      PINECONE_API_KEY: ${PINECONE_API_KEY}
      PINECONE_INDEX_HOST: ${PINECONE_INDEX_HOST}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      REDIS_URL: ${REDIS_URL}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      CRON_SCHEDULE: ${CRON_SCHEDULE}
    depends_on:
      - postgres
      - redis
  
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped


volumes:
  pg_data:
    driver: local
  redis-data:
    driver: local

networks:
  default:
    external:
      name: app-network