services:
  core-be:
    image: core-be:latest
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      SCRAPER_URL: ${SCRAPER_URL}
      PORT: ${PORT}