services:
  core-be:
    build:
      context: .
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      SCRAPER_URL: ${SCRAPER_URL}
      FE_URL: ${FE_URL}
      PORT: ${PORT}
      PINECONE_API_KEY: ${PINECONE_API_KEY}
      PINECONE_INDEX_HOST: ${PINECONE_INDEX_HOST}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      REDIS_URL: ${REDIS_URL}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

networks:
  app-net:
    external: true