// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/scraper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScrapeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeRequest) Reset() {
	*x = ScrapeRequest{}
	mi := &file_proto_scraper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeRequest) ProtoMessage() {}

func (x *ScrapeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeRequest.ProtoReflect.Descriptor instead.
func (*ScrapeRequest) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{0}
}

func (x *ScrapeRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ScrapeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeResponse) Reset() {
	*x = ScrapeResponse{}
	mi := &file_proto_scraper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeResponse) ProtoMessage() {}

func (x *ScrapeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeResponse.ProtoReflect.Descriptor instead.
func (*ScrapeResponse) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{1}
}

func (x *ScrapeResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ScrapeResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_scraper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{2}
}

type LeetCodeStatsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Reputation      int32                  `protobuf:"varint,1,opt,name=reputation,proto3" json:"reputation,omitempty"`
	Ranking         int32                  `protobuf:"varint,2,opt,name=ranking,proto3" json:"ranking,omitempty"`
	AcSubmissionNum []*SubmissionNum       `protobuf:"bytes,3,rep,name=ac_submission_num,json=acSubmissionNum,proto3" json:"ac_submission_num,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LeetCodeStatsResponse) Reset() {
	*x = LeetCodeStatsResponse{}
	mi := &file_proto_scraper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeetCodeStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeetCodeStatsResponse) ProtoMessage() {}

func (x *LeetCodeStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeetCodeStatsResponse.ProtoReflect.Descriptor instead.
func (*LeetCodeStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{3}
}

func (x *LeetCodeStatsResponse) GetReputation() int32 {
	if x != nil {
		return x.Reputation
	}
	return 0
}

func (x *LeetCodeStatsResponse) GetRanking() int32 {
	if x != nil {
		return x.Ranking
	}
	return 0
}

func (x *LeetCodeStatsResponse) GetAcSubmissionNum() []*SubmissionNum {
	if x != nil {
		return x.AcSubmissionNum
	}
	return nil
}

type SubmissionNum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Difficulty    string                 `protobuf:"bytes,1,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmissionNum) Reset() {
	*x = SubmissionNum{}
	mi := &file_proto_scraper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmissionNum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmissionNum) ProtoMessage() {}

func (x *SubmissionNum) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmissionNum.ProtoReflect.Descriptor instead.
func (*SubmissionNum) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{4}
}

func (x *SubmissionNum) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *SubmissionNum) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_proto_scraper_proto protoreflect.FileDescriptor

const file_proto_scraper_proto_rawDesc = "" +
	"\n" +
	"\x13proto/scraper.proto\x12\ascraper\"!\n" +
	"\rScrapeRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"@\n" +
	"\x0eScrapeResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\a\n" +
	"\x05Empty\"\x95\x01\n" +
	"\x15LeetCodeStatsResponse\x12\x1e\n" +
	"\n" +
	"reputation\x18\x01 \x01(\x05R\n" +
	"reputation\x12\x18\n" +
	"\aranking\x18\x02 \x01(\x05R\aranking\x12B\n" +
	"\x11ac_submission_num\x18\x03 \x03(\v2\x16.scraper.SubmissionNumR\x0facSubmissionNum\"E\n" +
	"\rSubmissionNum\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x01 \x01(\tR\n" +
	"difficulty\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count2K\n" +
	"\x0eScraperService\x129\n" +
	"\x06Scrape\x12\x16.scraper.ScrapeRequest\x1a\x17.scraper.ScrapeResponse2M\n" +
	"\x0fLeetCodeService\x12:\n" +
	"\bGetStats\x12\x0e.scraper.Empty\x1a\x1e.scraper.LeetCodeStatsResponseBGZEgithub.com/volodymyr-stishkovskyi-bachelor-thesis/core-be/proto;protob\x06proto3"

var (
	file_proto_scraper_proto_rawDescOnce sync.Once
	file_proto_scraper_proto_rawDescData []byte
)

func file_proto_scraper_proto_rawDescGZIP() []byte {
	file_proto_scraper_proto_rawDescOnce.Do(func() {
		file_proto_scraper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scraper_proto_rawDesc), len(file_proto_scraper_proto_rawDesc)))
	})
	return file_proto_scraper_proto_rawDescData
}

var file_proto_scraper_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_scraper_proto_goTypes = []any{
	(*ScrapeRequest)(nil),         // 0: scraper.ScrapeRequest
	(*ScrapeResponse)(nil),        // 1: scraper.ScrapeResponse
	(*Empty)(nil),                 // 2: scraper.Empty
	(*LeetCodeStatsResponse)(nil), // 3: scraper.LeetCodeStatsResponse
	(*SubmissionNum)(nil),         // 4: scraper.SubmissionNum
}
var file_proto_scraper_proto_depIdxs = []int32{
	4, // 0: scraper.LeetCodeStatsResponse.ac_submission_num:type_name -> scraper.SubmissionNum
	0, // 1: scraper.ScraperService.Scrape:input_type -> scraper.ScrapeRequest
	2, // 2: scraper.LeetCodeService.GetStats:input_type -> scraper.Empty
	1, // 3: scraper.ScraperService.Scrape:output_type -> scraper.ScrapeResponse
	3, // 4: scraper.LeetCodeService.GetStats:output_type -> scraper.LeetCodeStatsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_scraper_proto_init() }
func file_proto_scraper_proto_init() {
	if File_proto_scraper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scraper_proto_rawDesc), len(file_proto_scraper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_scraper_proto_goTypes,
		DependencyIndexes: file_proto_scraper_proto_depIdxs,
		MessageInfos:      file_proto_scraper_proto_msgTypes,
	}.Build()
	File_proto_scraper_proto = out.File
	file_proto_scraper_proto_goTypes = nil
	file_proto_scraper_proto_depIdxs = nil
}
