// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/scraper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScrapeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credly        []*CredlyResponse      `protobuf:"bytes,1,rep,name=credly,proto3" json:"credly,omitempty"`
	Leetcode      *LeetCodeStats         `protobuf:"bytes,2,opt,name=leetcode,proto3" json:"leetcode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeResponse) Reset() {
	*x = ScrapeResponse{}
	mi := &file_proto_scraper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeResponse) ProtoMessage() {}

func (x *ScrapeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeResponse.ProtoReflect.Descriptor instead.
func (*ScrapeResponse) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{0}
}

func (x *ScrapeResponse) GetCredly() []*CredlyResponse {
	if x != nil {
		return x.Credly
	}
	return nil
}

func (x *ScrapeResponse) GetLeetcode() *LeetCodeStats {
	if x != nil {
		return x.Leetcode
	}
	return nil
}

type CredlyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Issuer        string                 `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	IssuedDate    string                 `protobuf:"bytes,3,opt,name=issuedDate,proto3" json:"issuedDate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredlyResponse) Reset() {
	*x = CredlyResponse{}
	mi := &file_proto_scraper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredlyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredlyResponse) ProtoMessage() {}

func (x *CredlyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredlyResponse.ProtoReflect.Descriptor instead.
func (*CredlyResponse) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{1}
}

func (x *CredlyResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CredlyResponse) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *CredlyResponse) GetIssuedDate() string {
	if x != nil {
		return x.IssuedDate
	}
	return ""
}

type LeetCodeStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Reputation      int32                  `protobuf:"varint,1,opt,name=reputation,proto3" json:"reputation,omitempty"`
	Ranking         int32                  `protobuf:"varint,2,opt,name=ranking,proto3" json:"ranking,omitempty"`
	AcSubmissionNum []*SubmissionNum       `protobuf:"bytes,3,rep,name=acSubmissionNum,proto3" json:"acSubmissionNum,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LeetCodeStats) Reset() {
	*x = LeetCodeStats{}
	mi := &file_proto_scraper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeetCodeStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeetCodeStats) ProtoMessage() {}

func (x *LeetCodeStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeetCodeStats.ProtoReflect.Descriptor instead.
func (*LeetCodeStats) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{2}
}

func (x *LeetCodeStats) GetReputation() int32 {
	if x != nil {
		return x.Reputation
	}
	return 0
}

func (x *LeetCodeStats) GetRanking() int32 {
	if x != nil {
		return x.Ranking
	}
	return 0
}

func (x *LeetCodeStats) GetAcSubmissionNum() []*SubmissionNum {
	if x != nil {
		return x.AcSubmissionNum
	}
	return nil
}

type SubmissionNum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Difficulty    string                 `protobuf:"bytes,1,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmissionNum) Reset() {
	*x = SubmissionNum{}
	mi := &file_proto_scraper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmissionNum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmissionNum) ProtoMessage() {}

func (x *SubmissionNum) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmissionNum.ProtoReflect.Descriptor instead.
func (*SubmissionNum) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{3}
}

func (x *SubmissionNum) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *SubmissionNum) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_proto_scraper_proto protoreflect.FileDescriptor

const file_proto_scraper_proto_rawDesc = "" +
	"\n" +
	"\x13proto/scraper.proto\x12\ascraper\x1a\x1bgoogle/protobuf/empty.proto\"u\n" +
	"\x0eScrapeResponse\x12/\n" +
	"\x06credly\x18\x01 \x03(\v2\x17.scraper.CredlyResponseR\x06credly\x122\n" +
	"\bleetcode\x18\x02 \x01(\v2\x16.scraper.LeetCodeStatsR\bleetcode\"^\n" +
	"\x0eCredlyResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\x12\x1e\n" +
	"\n" +
	"issuedDate\x18\x03 \x01(\tR\n" +
	"issuedDate\"\x8b\x01\n" +
	"\rLeetCodeStats\x12\x1e\n" +
	"\n" +
	"reputation\x18\x01 \x01(\x05R\n" +
	"reputation\x12\x18\n" +
	"\aranking\x18\x02 \x01(\x05R\aranking\x12@\n" +
	"\x0facSubmissionNum\x18\x03 \x03(\v2\x16.scraper.SubmissionNumR\x0facSubmissionNum\"E\n" +
	"\rSubmissionNum\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x01 \x01(\tR\n" +
	"difficulty\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count2K\n" +
	"\x0eScraperService\x129\n" +
	"\x06Scrape\x12\x16.google.protobuf.Empty\x1a\x17.scraper.ScrapeResponseBGZEgithub.com/volodymyr-stishkovskyi-bachelor-thesis/core-be/proto;protob\x06proto3"

var (
	file_proto_scraper_proto_rawDescOnce sync.Once
	file_proto_scraper_proto_rawDescData []byte
)

func file_proto_scraper_proto_rawDescGZIP() []byte {
	file_proto_scraper_proto_rawDescOnce.Do(func() {
		file_proto_scraper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scraper_proto_rawDesc), len(file_proto_scraper_proto_rawDesc)))
	})
	return file_proto_scraper_proto_rawDescData
}

var file_proto_scraper_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_scraper_proto_goTypes = []any{
	(*ScrapeResponse)(nil), // 0: scraper.ScrapeResponse
	(*CredlyResponse)(nil), // 1: scraper.CredlyResponse
	(*LeetCodeStats)(nil),  // 2: scraper.LeetCodeStats
	(*SubmissionNum)(nil),  // 3: scraper.SubmissionNum
	(*emptypb.Empty)(nil),  // 4: google.protobuf.Empty
}
var file_proto_scraper_proto_depIdxs = []int32{
	1, // 0: scraper.ScrapeResponse.credly:type_name -> scraper.CredlyResponse
	2, // 1: scraper.ScrapeResponse.leetcode:type_name -> scraper.LeetCodeStats
	3, // 2: scraper.LeetCodeStats.acSubmissionNum:type_name -> scraper.SubmissionNum
	4, // 3: scraper.ScraperService.Scrape:input_type -> google.protobuf.Empty
	0, // 4: scraper.ScraperService.Scrape:output_type -> scraper.ScrapeResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_scraper_proto_init() }
func file_proto_scraper_proto_init() {
	if File_proto_scraper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scraper_proto_rawDesc), len(file_proto_scraper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_scraper_proto_goTypes,
		DependencyIndexes: file_proto_scraper_proto_depIdxs,
		MessageInfos:      file_proto_scraper_proto_msgTypes,
	}.Build()
	File_proto_scraper_proto = out.File
	file_proto_scraper_proto_goTypes = nil
	file_proto_scraper_proto_depIdxs = nil
}
